apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-storage-writer-grpc
  name: location-storage-writer-grpc
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30005
  selector:
    service: location-storage-writer-grpc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-storage-writer-grpc
  name: location-storage-writer-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-storage-writer-grpc
  template:
    metadata:
      labels:
        service: location-storage-writer-grpc
    spec:
      containers:
      - image: ujjwaldocker/location-storage-writer-grpc:latest
        name: location-storage-writer-grpc
        imagePullPolicy: Always
        env:
          - name: KAFKA_ADD
            valueFrom:
              configMapKeyRef:
                name: kafka-env
                key: KAFKA_ADD
      restartPolicy: Always
