apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-kafka-consumer
  name: location-kafka-consumer
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30006
  selector:
    service: location-kafka-consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-kafka-consumer
  name: location-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-kafka-consumer
  template:
    metadata:
      labels:
        service: location-kafka-consumer
    spec:
      containers:
      - image: ujjwaldocker/location-kafka-consumer:latest
        name: location-kafka-consumer
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_ADD
            valueFrom:
              configMapKeyRef:
                name: kafka-env
                key: KAFKA_ADD
      restartPolicy: Always
